# Generated by Django 2.2.7 on 2019-11-08 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='hole',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='played_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
