# Generated by Django 2.2.7 on 2019-11-18 17:32

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0002_auto_20191108_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='hole',
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='score',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
